apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Chart.Name }}-shared-file-store
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
  name: {{ .Chart.Name }}-shared-file-store
spec:
  replicas: {{ .Values.sharedFileStore.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-shared-file-store
      chart: {{ .Chart.Name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-shared-file-store
        chart: {{ .Chart.Name }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - env:
            - name: JAVA_OPTS
              value: {{ .Values.sharedFileStore.environment.java_opts }}
            - name: scheduler.cleanup.interval
              value: "86400000"
            - name: scheduler.content.age.millis
              value: "86400000"
          image: {{ .Values.sharedFileStore.image.repository }}:{{ .Values.sharedFileStore.image.tag }}
          name: {{ .Release.Name }}-shared-file-store
          ports:
            - containerPort: {{ .Values.sharedFileStore.image.internalPort }}
          volumeMounts:
            - mountPath: /tmp/Alfresco/sfs
              name: shared-file-store-data
      restartPolicy: {{ .Values.sharedFileStore.restartPolicy }}
      volumes:
        - name: shared-file-store-data
          persistentVolumeClaim:
            claimName: shared-file-store-data