apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Chart.Name }}-postgres
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
  name: {{ .Chart.Name }}-postgres
spec:
  replicas: {{ .Values.postgres.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-postgres
      chart: {{ .Chart.Name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-postgres
        chart: {{ .Chart.Name }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - args:
            - postgres
            - -c
            - max_connections=300
            - -c
            - log_min_messages=LOG
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}-postgres-configmap
          image: {{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}
          name: {{ .Release.Name }}-postgres
          ports:
            - containerPort: {{ .Values.postgres.image.internalPort }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -U {{ .Values.postgres.config.user }} -d "dbname={{ .Values.postgres.config.db }}" -h 127.0.0.1 -p {{ .Values.postgres.image.internalPort }}
            initialDelaySeconds: {{ .Values.postgres.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.postgres.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.postgres.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.postgres.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.postgres.livenessProbe.failureThreshold }}
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - -e
                - exec pg_isready -U {{ .Values.postgres.config.user }} -d "dbname={{ .Values.postgres.config.db }}" -h 127.0.0.1 -p {{ .Values.postgres.image.internalPort }}
            initialDelaySeconds: {{ .Values.postgres.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.postgres.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.postgres.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.postgres.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.postgres.readinessProbe.failureThreshold }}
      restartPolicy: {{ .Values.postgres.restartPolicy }}
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data

