apiVersion: v1
kind: ConfigMap
metadata:
  # the name of the config map
  name: {{ .Chart.Name }}-solr-configmap
  labels:
    app: {{ .Chart.Name }}-solr-configmap
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
data:
  ALFRESCO_SECURE_COMMS: {{ .Values.solr.config.comms }}
  JAVA_TOOL_OPTIONS: {{ .Values.solr.config.java_tool_options }}
  SOLR_ALFRESCO_HOST: {{ .Values.repository.service.name }}
  SOLR_ALFRESCO_PORT: "{{ .Values.repository.service.externalPort }}"
  SOLR_CREATE_ALFRESCO_DEFAULTS: {{ .Values.solr.config.createCore }}
  SOLR_SOLR_HOST: {{ .Values.solr.service.name }}
  SOLR_SOLR_PORT: "{{ .Values.solr.image.internalPort }}"
