apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ .Chart.Name }}-solr-data
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
  name: solr-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi